# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: release jar

on:
  push:
    branches: [ "main" ]
    
env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - run: mkdir staging && mv target/radio-hits-playlist-1.0-SNAPSHOT.jar target/radio-hits-playlist-${{ env.build-number }}.jar && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
        retention-days: 1
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB-TOKEN }}"
        automatic_release_tag: "${{ github.run_number }}"
        title: "Automated Build ${{ github.run_number }}"
        prerelease: true
        files: staging/*.jar
